# Generated by Django 4.2.9 on 2024-01-13 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/", verbose_name="Изображeние"
            ),
        ),
    ]
