# Generated by Django 4.2.9 on 2024-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/", verbose_name="Изображение"
            ),
        ),
    ]
