# Generated by Django 4.2.9 on 2024-01-28 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_rename_contact_contacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
    ]
