# Generated by Django 4.2.9 on 2024-02-10 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="date_created",
            new_name="data_created",
        ),
    ]
