# Generated by Django 4.2.9 on 2024-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_date_created_product_data_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="data_created",
            new_name="date_created",
        ),
    ]
