# Generated by Django 4.2.9 on 2024-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vers",
            field=models.PositiveIntegerField(default=0, verbose_name="Версия"),
        ),
    ]
