# Generated by Django 4.2.9 on 2024-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_rename_data_created_product_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(unique=True),
        ),
    ]
