# Generated by Django 4.2.9 on 2024-01-14 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_vers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="vers",
        ),
    ]
